.TH CBOARD 1
.SH NAME
cboard \- Simple chess game editor
.SH SYNOPSIS
.B cboard
[OPTIONS]
[PGN_FILE]
.SH DESCRIPTION
.B cboard
is chess game editor done with SDL.

It is designed to be controlled by keyboard using different modes.
Current mode is shown in lower left corner. See \fBMODES\fP
.SH OPTIONS
.TP
.B -c, --config \fIfile\fP
Path configuration file.
.TP
.B -f, --font \fIfile\fP
Path to TrueType font file.
.TP
.B --FEN-start
Starting position in FEN format.
.TP
.B --FEN-find
Set current move for position in FEN format.
.TP
.B -h, --help
Prints usage information.
.TP
.B -n, --number \fInumber\fP
Game number (starting from 0).
.TP
.B -o, --output \fIformat\fP
Output format (default none). Supported formats are: FEN, PGN.
.TP
.B -p, --pieces \fIdir\fP
Path to directory containing images of pieces, named with lowercase first
character of color and piece. Example: black bishop = bb.png
.TP
.B -v, --version
Prints version.
.SH MODES
.SS NORMAL
Main mode, other modes are entered from here.
.TP
.B q
Quit.
.TP
.B g
Enter GAME_LIST mode.
.TP
.B G
Toggle Game list statistics.
.TP
.B e
Enter EDIT mode.
.TP
.B f
Enter FILENAME mode.
.TP
.B n
Enter NUMBER mode.
.TP
.B s
Enter SAN mode.
.TP
.B t
Enter TAG mode.
.TP
.B T
Enter TRAINING mode.
.TP
.B v
Enter MOVE mode.
.TP
.B V
Enter POSITION mode.
.TP
.B a
Enter COMMENT mode after current move.
.TP
.B A
Enter COMMENT mode before current move.
.TP
.B c
Enter CLIPBOARD mode.
.TP
.B r
Rotate chessboard.
.TP
.B W
Write current game.
.TP
.B m
Start/stop machine 1.
.TP
.B M
Start/stop machine 2.
.TP
.B b
Show/hide machine output.
.TP
.B Space
Play best move from machine 1.
.TP
.B Shift-Space
Play best move from machine 2.
.TP
.B o
Start/stop explorer 1.
.TP
.B O
Start/stop explorer 2.
.TP
.B 0-9
Explorer events.
.TP
.B l, Arrow Right, Mouse Scroll Up
Go to next move.
.TP
.B h, Arrow Left, Mouse Scroll Down
Go to previous move.
.TP
.B j, Arrow Down
Go to first sub variation.
.TP
.B k, Arrow Up
Go to parent variation.
.TP
.B L, Shift-Arrow Right
Go to last move.
.TP
.B H, Shift-Arrow Left
Go to first move.
.TP
.B J, Shift-Arrow Down
Go to next sub variation.
.TP
.B K, Shift-Arrow Up
Go to previous sub variation.
.TP
.B u
Undo last destructive operation.
.TP
.B Ctrl-r
Redo last destructive operation.
.TP
.B z
Increase size of chessboard.
.TP
.B Z
Decrease size of chessboard.
.TP
.B +
Increase font size.
.TP
.B -
Decrease font size.
.TP
.B p
Promote current variation.
.TP
.B P
Promote current variation and delete old.
.TP
.B i
Insert moves from parent variation to current variation until they are valid.
.TP
.B d
Delete current variation.
.TP
.B D
Delete remaining moves after current move.
.TP
.B PageUp, Ctrl+u
Scroll notation up.
.TP
.B PageDown, Ctrl+d
Scroll notation down.
.SS GAME_LIST
.TP
.B q
Quit.
.TP
.B Escape
Return to NORMAL mode.
.TP
.B Return
Read current game.
.TP
.B r
Read game list from file.
.TP
.B p
Search current position.
.TP
.B j, Arrow Down
Move to next game.
.TP
.B f
Enter TEXTINPUT tag filter mode.
.TP
.B k, Arrow Up
Move to previous game.
.TP
.B /
Enter TEXINPUT search mode.
.TP
.B z
Increase size of chessboard.
.TP
.B Z
Decrease size of chessboard.
.TP
.B +
Increase font size.
.TP
.B -
Decrease font size.
.TP
.B c
Insert game title in comment after current move.
.TP
.B PageUp, Ctrl+u
Scroll game list up.
.TP
.B PageDown, Ctrl+d
Scroll game list down.
.SS TAG_FILTER
TEXTINPUT mode. First the tag name and operator is inputted.
Tag name and operator are split by single space.
If it already exists, it will be edited - otherwise new tag filter is created.
.TP
.B Return
Confirm tag name and operator. And enter TEXTINPUT mode for editing tag filters.
Tag filter will be removed if its value is empty string.
.TP
.B OPERATORS
.TP
.B =
Exact match.
.TP
.B ~
Case insensitive substring.
.TP
.B >
Greater than.
.TP
.B <
Lower than.
.SS TEXTINPUT
Pressed keys are inserted as text.
.TP
.B sort
Sort game list by tag.
Tag can be "File" in which case the game list is just read from File.
Correct values are Asc or Desc.
.B Escape
Return to previous mode.
.TP
.B Ctrl-u
Delete all text.
.TP
.B Left Arrow
Move cursor left.
.TP
.B Right Arrow
Move cursor right.
.TP
.B Backspace
Delete character before cursor.
.TP
.B Delete
Delete character after cursor.
.SS EDIT
.TP
.B Mouse Click Left
Insert current piece at clicked square.
.TP
.B Mouse Click Right
Clear piece at clicked square.
.TP
.B q
Quit.
.TP
.B c
Clear board.
.TP
.B s
Set starting position.
.TP
.B f
Import FEN from clipboard.
.TP
.B r
Rotate chessboard.
.TP
.B 0
Change color.
.TP
.B 1
Select pawn of current color.
.TP
.B 2
Select knight of current color.
.TP
.B 3
Select bishop of current color.
.TP
.B 4
Select rook of current color.
.TP
.B 5
Select queen of current color.
.TP
.B 6
Select king of current color.
.SS FILENAME
TEXTINPUT mode. Filename is used for reading and writing.
.SS NUMBER
TEXTINPUT mode. Number represents game sequence.
If value is "a" game is added at the end of file.
.SS SAN
It is TEXINPUT mode. Correct SAN moves are accepted and played.
.TP
.B Return
If move is correct it is played.
.SS TAG
TEXTINPUT mode. First the tag name is inputted.
If it already exists, it will be edited - otherwise new tag is created.
.TP
.B Return
Confirm tag name. And enter TEXTINPUT mode for editing tags.
Tag will be removed if its value is empty string (except for required 7 tags).
.SS TRAINING
TEXTINPUT mode. Notation is hidden.
After user plays move that exists in notation the opponents move will be
played automatically - starting with main line.
Move can be inserted with mouse or in SAN format.
There are 3 avaliable commands besides correct SAN moves: Restart, Repeat and
Next.
Restart will start from begining - first game and its main line.
Repeat will replay current line again.
Next will proceed to the next line or next file if all lines in current game
are finished.

.SS MOVE
Move annotation.
.TP
.B q
Quit.
.TP
.B r
Rotate chessboard.
.TP
.B j, Arrow Down
Select next move NAG.
.TP
.B k, Arrow Up
Select previous move NAG.
.TP
.B x, Backspace
Delete move NAG.
.TP
.B Escape
Return to NORMAL mode.
.SS POSITION
Position annotation.
.TP
.B q
Quit.
.TP
.B r
Rotate chessboard.
.TP
.B j, Arrow Down
Select next position NAG.
.TP
.B k, Arrow Up
Select previous position NAG.
.TP
.B x, Backspace
Delete position NAG.
.TP
.B Space
Input position NAG from machine 1.
.TP
.B Shift-Space
Input position NAG from machine 2.
.TP
.B Escape
Return to NORMAL mode.
.SS COMMENT
TEXTINPUT mode. Comment is inserted after/before current move.
.SS CLIPBOARD
.TP
.B q
Quit.
.TP
.B f
Copy current FEN to clipboard.
.TP
.B Escape
Return to NORMAL mode.
.SH EXPLORER
Explorer is external program that comunicates with cboard over standard input and output.
.SS COMMANDS
Commands are send from cboard to explorer.
.TP
.B fen \fIstring\fP
Current position in cboard.
.SS RESPONSE
Explorer should return newline separated strings.
Response will be shown in cboard without modification.
.SH CONFIGURATION
Configuration is done by line separated key=value.
Lines starting with # are skipped.
Example config is located in /usr/share/cboard/config.
.TP
.B machine_1_exe, machine_2_exe
Absolute path to engine executable.
.BI machine_1_exe=/bin/stockfish
.TP
.B machine_1_param,machine_2_param
Engine command line parameters, can be used multiple times.
.BI machine_2_param=--logfile=/home/user/log
.TP
.B machine_1_uci_option_start, machine_2_uci_option_start
Option does not take value.
Lines after this are passed to engine.
.TP
.B machine_1_uci_option_end, machine_2_uci_option_end
End literal input.
.TP
.B explorer_1_exe, explorer_2_exe
Absolute path to explorer executable.
.SH FILES
.I $HOME/.config/cboard/config
Default config location.
